interface ICloud {
  name: string,
  code: string,
  density: string,
}

export const clouds: ICloud[] = [
  {
    name: 'no significant clouds',
    code: 'NSC',
    density: 'no clouds',
  },
  {
    name: 'few',
    code: 'FEW',
    density: '1/8 - 2/8',
  },
  {
    name: 'scattered',
    code: 'SCT',
    density: '3/8 - 4/8',
  },
  {
    name: 'broken',
    code: 'BKN',
    density: '5/8 – 7/8',
  },
  {
    name: 'overcast',
    code: 'OVC',
    density: '8/8',
  },
];

export const rvrTrend: { [k: string]: string } = {
  U: 'Upward',
  D: 'Downward',
  N: 'No distinct tendency'
};

export const weather: { [k: string]: string } = {
  '-': 'light intensity',
  '+': 'heavy intensity',
  VC: 'in the vicinity',
  MI: 'shallow',
  PR: 'partial',
  BC: 'patches',
  DR: 'low drifting',
  BL: 'blowing',
  SH: 'showers',
  TS: 'thunderstorm',
  FZ: 'freezing',
  RA: 'rain',
  DZ: 'drizzle',
  SN: 'snow',
  SG: 'snow grains',
  IC: 'ice crystals',
  PL: 'ice pellets',
  GR: 'hail',
  GS: 'small hail',
  UP: 'unknown precipitation',
  FG: 'fog',
  VA: 'volcanic ash',
  BR: 'mist',
  HZ: 'haze',
  DU: 'widespread dust',
  FU: 'smoke',
  SA: 'sand',
  PY: 'spray',
  SQ: 'squall',
  PO: 'dust or sand whirls',
  DS: 'duststorm',
  SS: 'sandstorm',
  FC: 'funnel cloud',
  MIFG: 'TEST',
  BCFG: 'TEST',
  PRFG: 'TEST',
  REBLSN: 'Moderate/heavy blowing snow (visibility significantly reduced)reduced',
  REDS: 'Dust Storm',
  REFC: 'Funnel Cloud',
  REFZDZ: 'Freezing Drizzle',
  REFZRA: 'Freezing Rain',
  REGP: 'Moderate/heavy snow pellets',
  REGR: 'Moderate/heavy hail',
  REGS: 'Moderate/heavy small hail',
  REIC: 'Moderate/heavy ice crystals',
  REPL: 'Moderate/heavy ice pellets',
  RERA: 'Moderate/heavy rain',
  RESG: 'Moderate/heavy snow grains',
  RESHGR: 'Moderate/heavy hail showers',
  RESHGS: 'Moderate/heavy small hail showers',
  RESHPL: 'Moderate/heavy ice pellet showers',
  RESHRA: 'Moderate/heavy rain showers',
  RESHSN: 'Moderate/heavy snow showers',
  RESN: 'Moderate/heavy snow',
  RESS: 'Sandstorm',
  RETS: 'Thunderstorm',
  REUP: 'Unidentified precipitation (AUTO obs. only)',
  REVA: 'Volcanic Ash',
};

export const trends: { [k: string]: string } = {
  NOSIG: 'No significant change',
  BECMG: 'BECMG',
  TEMPO: 'TEMPO',
  NSW: 'No significant weather',
  NSC: 'No significant clouds',
};
